
# curl 'https://www.consorcioservopa.com.br/_app/ajax/representantes.php' \
#  -H 'accept: */*' \
#  -H 'accept-language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7' \
#  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
#  -b '_fbp=fb.2.1763004890434.709720567571997204; _gcl_au=1.1.1913658000.1763004890; _ga=GA1.1.230348731.1763004891; _clck=7gb1sg%5E2%5Eg0z%5E0%5E2143; nvg56465=16ac12866341abfa1e286b420c10|0_318; voxusmediamanager_cd_attr_status=true; _hjSessionUser_1312257=eyJpZCI6IjhkODA2NWQ0LTNjOTgtNTZkZC05M2MxLTE2NGIxNzVlZGQwNiIsImNyZWF0ZWQiOjE3NjMwMDQ4OTA1NDAsImV4aXN0aW5nIjp0cnVlfQ==; token_servopa=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM4Mjc2NSwidXNlcm5hbWUiOiJ1c2VyLWJjYjY3NDBhZWQzNjQ4YThhOTg2MzZhZTFkNDA3ZmU1IiwiZnVsbE5hbWUiOiJhbm9ueW1vdXMiLCJ0ZW5hbnRVcmkiOiJzZXJ2b3BhIiwibm9tZVBhcmNlaXJvIjpudWxsLCJpYXQiOjE3NjMwMDY0NDAsImV4cCI6MTc5NDU0MjQ0MH0.n6GpiDicNPuBbbBkXcqwHsxUTIFcodiySDSEl3AKxDk; PHPSESSID=95tc9eeuii3hdj0im6u26jbrgk; _ga_KBYTHP1323=GS2.1.s1763058622$o2$g0$t1763058622$j60$l0$h1551457089; _hjSession_1312257=eyJpZCI6ImFjNDYzYzBhLTY4OTYtNDgzNy1hNjc3LTEyNjM1ZjdiNmE1YiIsImMiOjE3NjMwNTg2MjI5NTAsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjowfQ==; _clsk=1gc0oty%5E1763058623662%5E1%5E1%5El.clarity.ms%2Fcollect; voxusmediamanager_id=17630048932960.015039902297837249zor2m78rha; vx_identifier=18; voxusmediamanager_ip=138.255.179.88; measurement_id=G-KBYTHP1323; voxus_last_entry_before_impression=1763058633' \
#  -H 'dnt: 1' \
#  -H 'origin: https://www.consorcioservopa.com.br' \
#  -H 'priority: u=1, i' \
#  -H 'referer: https://www.consorcioservopa.com.br/onde-encontrar' \
#  -H 'sec-ch-ua: "Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"' \
#  -H 'sec-ch-ua-mobile: ?0' \
#  -H 'sec-ch-ua-platform: "Linux"' \
#  -H 'sec-fetch-dest: empty' \
#  -H 'sec-fetch-mode: cors' \
#  -H 'sec-fetch-site: same-origin' \
#  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36' \
#  -H 'x-requested-with: XMLHttpRequest' \
#  --data-raw 'estado=RS'

  				49.799.242 RAFAEL KERN ALVES
  				50.413.837 CESAR ARTUR PILGER
  				52.663.359 ISABEL CRISTINA DA LUZ DIOGO
  				52.936.420 PAULO ROBERTO FINK
  				53.808.013 JULIANA SOARES BORBA
  				55.035.913 EWERTON NUNES LEAL
  				59.166.899 ELISANGELA MARTINS INACIO
  				60.330.900 THAINARA PEREIRA DA SILVA BRUM
  				60.910.400 LUCIANE GOMES DUTRA
  				61.173.435 ROSANE RAMOS RODRIGUES
  				A ACQUAMARINHA CORRETORA E CONSULTORA DE SEGUROS L
  				AFFLUENCE SOLUCOES FINANCEIRAS LTDA
  				AJ CONSORCIOS E SOLUCOES FINANCEIRAS LTDA
  				ALCI ALEXANDRE JUNIOR 00680093052
  				ALEXANDRE BARREIRO SANTOS
  				ANDRIARA ROCHA DE BRUM
  				ANECON ALIANCA NACIONAL DOS EXECUTIVOS DE CONSORCI
  				ARAUJO INVESTIMENTOS LTDA
  				ARG CONSULTORIA EM VENDAS LTDA
  				ARM INVESTIMENTOS LTDA
  				ARMARES CORRETORA DE SEGUROS EIRELI
  				ASSERTIVA COR SEGS LTDA
  				AUREA CONSORCIOS E INVESTIMENTOS LTDA
  				BEILKE & BEILKE COMERCIO E INTERMEDICAO DE CONSORC
  				BENISA MACIEL IMOBILIARIA LTDA
  				BEZ BATTI CORRETORA DE SEGUROS LTDA
  				BOM NEGOCIO CONSORCIOS LTDA
  				BORGTE E BORGTE LTDA
  				C V K SOLUCOES COMERCIAIS LTDA
  				CABRAL D FERRETTI LTDA
  				CAMARGO CONSORCIOS LTDA
  				CANAA SOLUCOES FINANCEIRAS LTDA
  				CANTERLE JP CORRETORA DE SEGUROS LTDA
  				CAPITALIZZA PRIME INVESTIMENTOS LTDA
  				CARWAY SUL VEICULOS LTDA
  				CARWAY SUL VEICULOS LTDA
  				CARWAY SUL VEICULOS LTDA
  				CARWAY SUL VEICULOS LTDA
  				CASA NOSTRA CORRETORA DE SEGUROS LTDA
  				CBJ SOLUCOES FINANCEIRAS LTDA
  				CIMA SOLUCOES FINANCEIRAS LTDA
  				CL CONSORCIOS LTDA
  				CLAUDIO NEIMAIER CORRETOR DE SEGUROS E CONSORCIO L
  				COLTRO INTERMEDIACAO DE CONSRCIOS LTDA
  				CONVICTA SOLUCOES & EXPANSAO DE NEGOCIOS LTDA
  				CORSO CONSORCIOS E REPRESENTACOES LTDA
  				CREATOR CORRETORA DE SEGUROS LTDA
  				CREDIICON CONSORCIOS LTDA
  				CREDILLAN CONSORCIOS E INVESTIMENTOS LTDA
  				CREDIM CREDITOS E INVESTIMENTOS LTDA
  				CRISTIANE GONCALVES DA SILVA LTDA
  				DANIEL LIMA ARAUJO
  				DARTEC SOLUCOES EMPRESARIAIS LTDA
  				DERMAR REPRESENTACOES COMERCIAIS LTDA
  				DIJON COMERCIO DE VEICULOS LTDA
  				DIJON COMERCIO DE VEICULOS LTDA
  				DIJON COMERCIO DE VEICULOS LTDA
  				DIJON COMERCIO DE VEICULOS LTDA
  				DM CONSORCIOS LTDA
  				DMAIS INVESTIMENTOS LTDA
  				DUO REPRESENTACOES E SERVICOS LTDA
  				EDUARDA VIEIRA LTDA
  				EICKHOFF CORRETORA DE SEGUROS LTDA
  				EMILIO NUNES CORRETORA DE SEGUROS LTDA
  				ESO SERVICOS FINANCEIROS LTDA
  				EXATTA CORRETORA DE SEGUROS E CONSORCIOS LTDA
  				FABRINA FIGUEIREDO HOFFMANN
  				FARINA E FARINA CORRETORA DE SEGUROS E CONSORCIOS
  				FEDATTO FRANCHISING CORRETORAS DE SEGUROS LTDA
  				FELIPE ZANON BOCK
  				FERUS INVESTIMENTOS E CORRETORA DE SEGUROS LTDA
  				FORTE CONSORCIOS LTDA
  				FOURCON CONSORCIOS LTDA
  				FR CONSORCIOS LTDA
  				FRITZ CORRETORA DE SEGUROS LTDA
  				FSEG CORRETORA DE SEGUROS E CONSORCIOS LTDA
  				GAUER CONSORCIOS LTDA
  				GESSEG ADMINISTRADORA E CORRETORA DE SEGUROS LTDA
  				GIRARDI & ZIEGLER LTDA
  				GLH SOLUCOES FINANCEIRAS LTDA
  				GLOBAL AUTOMOTIVE COMERCIO DE VEICULOS LTDA
  				GODOY CORRETOR DE SEGUROS LTDA
  				GR WEBER TORO CORRETORA DE SEGUROS LTDA
  				GRATTA CORRETORA DE SEGUROS LTDA
  				GREGOLON CORRETORA DE SEGUROS LTDA
  				GUERINI E SCHMITT LTDA
  				H & H CONSULTORIA EM TECNOLOGIA LTDA
  				HSO NEGOCIOS LTDA
  				HUBLY360 SOLUCOES EM TECNOLOGIA LTDA
  				INNVEST CONSULTORIA FINANCEIRA LTDA
  				INVESTBENS NEGOCIOS E SOLUCOES LTDA
  				INVISTA REPRESENTACAO COMERCIAL LTDA
  				ITM CONSORCIOS LTDA
  				J H O BECCON LTDA
  				JAIRA MIRANDA DOS SANTOS LTDA
  				JOAO ANTONIO MACHADO E CIA LTDA
  				JP PROMOTORA DE VENDAS LTDA
  				K. F. DOS SANTOS LTDA
  				KONCEITO CORRETORA E ADMINISTRADORA DE SEGUROS E C
  				LACERDA SEGUROS & INVESTIMENTOS LTDA
  				LAGOROCHA CORRETORA DE SEGUROS E CONSORCIOS LTDA
  				LAMPERTI CONSORCIOS LTDA
  				LIDER CONSORCIOS LTDA
  				LTS AGENCIAMENTO E NEGOCIOS LTDA
  				LUIGGI VENDAS E CONSORCIOS LTDA
  				M. DURGANTE DO NASCIMENTO LTDA
  				MACH NEGOCIOS E SERVICOS LTDA
  				MAG CONSORCIOS E INVESTIMENTOS LTDA
  				MAGDA GENESSI CESAR LONGARAY 43699677087
  				MAGGISEG CORRETORA DE SEGUROS LTDA
  				MAIARA A. S. PINHEIRO SERVICOS FINANCEIROS
  				MARIA ELOISA PACHECO LTDA
  				MARTA CONSORCIOS LTDA
  				MASTER COMERCIO E REPRESENTACOES LTDA
  				MASTER CROP CONSORCIOS LTDA
  				MASTER SIERRA CONSORCIOS LTDA
  				MATAVELI LOCACOES E VENDAS LTDA
  				MCA SOLUCOES FINANCEIRAS LTDA
  				MD23 CONSULTORIA EMPRESARIAL LTDA
  				MEGAINVEST COMERCIO E REPRESENTACAO LTDA
  				MIDAS CONSORCIOS REPRESENTACAO E COMERCIO LTDA
  				NOSSA TERRA CORRETORA DE SEGUROS LTDA
  				ORIGEM CAPITAL CONSULTORIA E SERVICOS LTDA
  				PAMELA EDUARDA DOS REIS MORAES 02526470099
  				PATRICIA CHAVES DIAS DA COSTA LTDA
  				PENSE ADMINISTRACAO DE CONSORCIOS LTDA
  				PLATINUM NEG IMOB COMERCIO E REPRESENTACOES LTDA
  				PRIME SOLUCOES FINANCEIRAS LTDA
  				PROJECAO CONSORCIOS LTDA
  				PS ADVISOR CORRETAGEM DE SEGUROS LTDA
  				R&D SOLUCOES FINANCEIRAS LTDA
  				RAFAEL BARTELLT PEREIRA LTDA
  				RAQUEL DA SILVA RODRIGUES 38176955000
  				RAQUEL FIGUEIRO CONSORCIOS LTDA
  				REDDERE SOLUCOES FINANCEIRAS LTDA
  				RELICARIO NEGOCIOS IMOBILIARIOS LTDA
  				RENE TEIXEIRA GULARTE
  				RNC REDE NACIONAL DE CAMBIO LTDA
  				ROBERT STAR IMOVEIS LTDA
  				ROCKS SERVICOS DE INTERMEDIACAO E APOIO ADMINISTRA
  				RODOLL CORRETORA DE SEGUROS LTDA
  				RONALDO KEMERICH DOS REIS REPRESENTACAO LTDA
  				RXM INVESTIMENTOS LTDA
  				SENDA INVESTIMENTOS E CONSULTORIA LTDA
  				SERRANA CONSORCIOS CORRETOR AUTORIZADO LTDA
  				SOLO CORRETAGEM DE SEGUROS LTDA
  				STIEVEN REPRESENTACOES LTDA ME
  				STURMER INVESTIMENTOS LTDA
  				SWEET HOME AUDIO VIDEO AUTOMACAO LTDA
  				SYLCON CONSORCIOS, FINANCIAMENTOS E CORRETAGEM DE
  				SYROS FINANCIAL E CORRETORA DE SEGUROS LTDA
  				TATIANA Z. DA ROCHA LTDA
  				TIAGO BORGES REPRESENTACOES
  				UNIAO INVEST PROMOCAO EM VENDAS LTDA
  				UNIFIQUE SERVICOS FINANCEIROS LTDA
  				UNIPART CORRETORA DE SEGUROS LTDA
  				UP PLATAFORMA DE NEGOCIOS LTDA
  				V F FINANCEIRA LTDA
  				VALLERIUS CONSORCIOS LTDA
  				VANZELLA NETWORK E INTERMEDIACAO DE NEGOCIOS LTDA
  				VASCONCELOS IMOBILIARIA E CORRETORA DE SEGUROS LTD
  				VC CORRETORA DE SEGUROS LTDA
  				VENT CORRETORA DE SEGUROS E IMOVEIS LTDA
  				VIABILIZE SOLUCOES EMPRESARIAS LTDA
  				WALLAUER CONSORCIOS LTDA
  				WP8 CORRETORA DE SEGUROS LTDA
  				WV SOLAR LTDA
  				X10 SERVICOS FINANCEIROS LTDA
